apiVersion: apps/v1
kind: Deployment
metadata:
  name: osp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: osp-app
  template:
    metadata:
      labels:
        app: osp-app
    spec:
      containers:
      - name: osp-app
        image: nginx
        envFrom:
          - secretRef:
             name: test-secret            
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
