apiVersion: v1
kind: Secret
metadata:
  name: osp-secret
data:
  ConnectionStrings: bXktYXBw
  OpenSourcePortalApplicationContext: Server=tcp:devsecops-aks-test-server.database.windows.net,1433;Initial Catalog=DB-CDT-ODS-PUB-SWEIS-OSP-W-P-001-DEV-AKS;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=ActiveDirectoryManagedIdentity;